name: all_log
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.3
  provider: ^6.0.3
  http: ^0.13.5
  geolocator: ^9.0.1
  flutter_spinkit: ^5.1.0
  rflutter_alert: ^2.0.4
  geocoding: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  assets:
    - images/
  uses-material-design: true
